name: linux
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"

jobs:
  build:
    env:
      buildDir: "${{ github.workspace }}/build/"
      CCACHE_DIR: "${{ github.workspace }}/ccache/"
      CCACHE_BASEDIR: "${{ github.workspace }}/ccache/"
      SCCACHE_DIR: "${{ github.workspace }}/ccache/"
      SCCACHE_BASEDIR: "${{ github.workspace }}/ccache/"

    name: build on linux
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get current date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: install non-vcpkg dependencies
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y ccache gcc-11 g++-11 cpp-11 gperf build-essential libgl1-mesa-dev libxkbcommon-x11-0 \
            libpulse-dev libxcb-util1 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
            libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 \
            libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb1 \
            at curl unzip tar libxt-dev libxaw7-dev cifs-utils \
            zip libx11-dev libxkbcommon-x11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxinerama-dev libxxf86vm-dev \
            libxcursor-dev yasm libnuma1 libnuma-dev python-six python3-six python-yaml \
            flex libbison-dev autoconf libudev-dev libncurses5-dev libtool libxrandr-dev \
            xutils-dev dh-autoreconf autoconf-archive libgles2-mesa-dev ruby-full \
            pkg-config meson libxext-dev libxfixes-dev libxrender-dev \
            libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-util0-dev \
            libxkbcommon-dev libxcb-keysyms1-dev \
            libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev \
            libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev \
            libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xinput-dev libkrb5-dev \
            libxcb-res0-dev python3-setuptools python3-mako python3-pip libxcb-cursor0
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          modules: "qtmultimedia"
          cache: true


      - name: cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-build-${{ env.DATE }} }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure & Build
        run: |
          ./scripts/dist_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: arclight-linux-x64
          path: bin/*
