name: macOS
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"

jobs:
  build:
    env:
      buildDir: "${{ github.workspace }}/build/"
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    name: build on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      - name: Get current date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: install non-vcpkg dependencies
        env:
          HOMEBREW_NO_ANALYTICS: "ON"
          HOMEBREW_NO_AUTO_UPDATE: "ON"
          HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
          HOMEBREW_NO_INSTALL_CLEANUP: "ON"
        run: |
          brew install automake ninja ccache

      - name: Set up ccache
        run: |
          ccache --set-config=cache_dir=${{ github.workspace }}/.ccache
          ccache --set-config=max_size=500M
          ccache --set-config=compression=true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          modules: "qtmultimedia"
          cache: true

      - name: cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-build-${{ env.DATE }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure & Build
        run: |
          ./scripts/dist_mac.sh

      - uses: actions/upload-artifact@v4
        with:
          name: arclight-macOS-x64
          path: |
            bin/*.dmg
            LICENSE
            LICENSE.LGPL
            README.md

      - name: ccache stats
        run: |
          ccache -s
