name: windows
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"

jobs:
  build:
    env:
      buildDir: "${{ github.workspace }}/build/"
      CCACHE_DIR: "${{ github.workspace }}/ccache/"
      CCACHE_BASEDIR: "${{ github.workspace }}/ccache/"
      SCCACHE_DIR: "${{ github.workspace }}/ccache/"
      SCCACHE_BASEDIR: "${{ github.workspace }}/ccache/"

    name: build on windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: install dependencies
        if: matrix.os == 'windows-2019'
        run: |
          choco install sccache ninja

      - name: Get current date
        run: |
          echo "DATE=$(Get-Date -Format yyyy-MM-dd)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.0
          cache: true

      - name: cache ccache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-build-${{ env.DATE }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure & Build
        run: .\scripts\dist_win.bat

      - uses: actions/upload-artifact@v2
        with:
          name: arclight-windows-x64
          path: bin/*
