name: windows
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"

jobs:
  build:
    env:
      buildDir: "${{ github.workspace }}/build/"

    name: build on windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest

      - name: install dependencies
        run: |
          choco install ccache ninja

      - name: Get current date
        run: |
          echo "DATE=$(Get-Date -Format yyyy-MM-dd)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: setup ccache
        run: |
          ccache --set-config=cache_dir=${{ github.workspace }}/.ccache
          ccache --set-config=max_size=5G
          ccache --set-config=compression=true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          modules: "qtmultimedia"
          cache: true

      - name: cache ccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-build-${{ env.DATE }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure & Build
        run: .\scripts\dist_win.bat

      - uses: actions/upload-artifact@v4
        with:
          name: arclight-windows-x64
          path: bin/*

      - name: ccache stats
        run: |
          ccache -s
