name: windows
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.pdf"

jobs:
  build:
    env:
      buildDir: "${{ github.workspace }}/build/"
      vcpkg-tag: "2022.09.27"
      VCPKG_ROOT: "c:/vcpkg_root/"
      VCPKG_DEFAULT_BINARY_CACHE: "c:/vcpkg_root/.cache"
      CCACHE_DIR: "${{ github.workspace }}/ccache/"
      CCACHE_BASEDIR: "${{ github.workspace }}/ccache/"
      SCCACHE_DIR: "${{ github.workspace }}/ccache/"
      SCCACHE_BASEDIR: "${{ github.workspace }}/ccache/"

    name: build on windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: install dependencies
        if: matrix.os == 'windows-2019'
        run: |
          choco install sccache ninja

      - name: Get current date
        run: |
          echo "DATE=$(Get-Date -Format yyyy-MM-dd)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.3.2
          cache: true

      - name: download vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg c:/vcpkg_root
          pushd c:/vcpkg_root
          git checkout --force ${{ env.vcpkg-tag }}
          ./bootstrap-vcpkg.bat
          popd

      - name: cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg/.cache
            ${{ github.workspace }}/ccache
          key: ${{ runner.os }}-build-${{ env.vcpkg-tag }}-${{ env.DATE }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Make cache dir
        run: mkdir "${{env.VCPKG_DEFAULT_BINARY_CACHE}}"

      - name: Configure & Build
        run: .\scripts\dist_win.bat

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: vcpkg-logs
          path: ${{env.VCPKG_ROOT}}/buildtrees/**/*.log

      - uses: actions/upload-artifact@v2
        with:
          name: arclight-windows-x64
          path: bin/*
